### ISSUE TITLE
Core from config set not created

### ISSUE THREAD

**Issue by gambry** [wodby/solr#15]
Hi,

The Solr container doesn't create the default core from Search API Solr config set as described in the README.md file.

I've got the `solr` service setup in this way:
```
image: wodby/solr:$SOLR_TAG
container_name: "${PROJECT_NAME}_solr"
environment:
  SOLR_DEFAULT_CONFIG_SET: $SOLR_CONFIG_SET
  SOLR_HEAP: 1024m
```

Where in my .env file $SOLR_TAG is `7-4.7.4` and $SOLR_CONFIG_SET is `search_api_solr_4.1.6`.

The Solr instance is up and running, I can connect to it but there are no cores. Also opening a console into the container and `ls /opt/solr/server/solr/configsets` lists all search_api_solr config sets one would expect.

I had to manually fire in the browser `http://solr.myproject-docker-host:8000/solr/admin/cores?action=CREATE&name=default&configSet=search_api_solr_4.1.6&instanceDir=default` in order for the core to be created.
